---
# ./static-assignments/create-ec2.yml

- name: Launch EC2 instance
  hosts: localhost
  connection: local
  tasks:
  - include_vars: ../vars/ec2-vars.yml
  - name: Launch task
    local_action:
      module: amazon.aws.ec2_instance
      instance_type: "{{ instance_type }}"
      image_id: "{{ image }}"
      wait: yes
      key_name: "{{ keypair }}"
      region: "{{ region }}"
      count: "{{ count }}"
      security_group: "{{ security_group }}"
      tags:
       Name: "Myec2instance"