---
# ./static-assignments/create-ec2.yml

- name: Launch EC2 instance
  hosts: localhost
  connection: local
  tasks:
  - include_vars: ../vars/ec2-vars.yml
  - name: Launch task
    local_action:
      module: ec2
      group: "{{ security-group }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: yes
      keypair: "{{ keypair }}"
      region: "{{ region }}"
      count: "{{ count }}"
    register: ec2

  - name: Tag Instance
    local_action:
      module: ec2_tag
      resource: "{{ item.id }}"
      region: "{{ region }}"
      state: "{{ present }}"
    with_items: "{{ ec2.instances }}"
    args:
      tags:
        Name: MyEc2Instance