---
- hosts: localhost
  become: true
  connection: local

  roles:
    - role: geerlingguy.docker

  tasks:
    - name: Install Pip
      apt:
        name: python3-pip
        state: present

    - name: Install Docker
      pip:
        name: docker
        state: present
