---
# ./static-assignments/create-sgr.yml

- name: Create Security Group
  hosts: localhost
  connection: local
  tasks:
    - include_vars: ../vars/ec2-vars.yml

    - name: Creating security group
      local_action:
        module: ec2_group
        name: "{{ security_group }}"
        description: Security group for instance
        region: "{{ region }}"
        state: present
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: aws_sg

    - name: "Tag security group"
      local_action:
        module: ec2_tag
        resource: "{{ aws_sg.group_id }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: sg-common

